Host: 0.0.0.0
Port: 8080
DataDir: data
#Auth:
#  admin: 123456
Log:
  Level: info
  #Filename: /var/log/mixed-socks/mixed-socks.log
  MaxBackups: 7
  MaxSize: 50   # megabytes
  MaxAge: 7     # days
  Compress: true # compress log