definitions:
  api.Info:
    properties:
      buildTime:
        type: string
      git:
        properties:
          branch:
            type: string
          commit:
            type: string
          url:
            type: string
        type: object
      go:
        properties:
          arch:
            type: string
          os:
            type: string
          version:
            type: string
        type: object
      user:
        properties:
          email:
            type: string
          name:
            type: string
        type: object
      version:
        type: string
    type: object
  api.JSONResult:
    properties:
      code:
        example: 0
        type: integer
      data: {}
      message:
        example: 消息
        type: string
    type: object
  service.Conf:
    properties:
      cidr:
        example:
        - 0.0.0.0/0
        items:
          type: string
        type: array
      host:
        example: 0.0.0.0
        type: string
      port:
        example: 8090
        type: integer
      timeout:
        example: 30s
        type: string
    type: object
  service.User:
    properties:
      cidr:
        example:
        - 0.0.0.0/0
        items:
          type: string
        type: array
      disabled:
        example: false
        type: boolean
      name:
        example: name
        type: string
      pass:
        example: "123456"
        type: string
      remark:
        example: 小明
        type: string
    required:
    - name
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: support socks4, socks5, http proxy all in one
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Mixed-Socks
  version: v2.0.0
paths:
  /api/config:
    get:
      description: get mixed socks config
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONResult'
      security:
      - BasicAuth: []
      summary: get
      tags:
      - Config
    post:
      description: update mixed socks config
      parameters:
      - description: config
        in: body
        name: scripts
        required: true
        schema:
          $ref: '#/definitions/service.Conf'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONResult'
      security:
      - BasicAuth: []
      summary: save
      tags:
      - Config
  /api/reload:
    post:
      description: reload mixed socks config
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONResult'
      security:
      - BasicAuth: []
      summary: reload
      tags:
      - Operate
  /api/start:
    post:
      description: start mixed socks
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONResult'
      security:
      - BasicAuth: []
      summary: start
      tags:
      - Operate
  /api/state:
    get:
      description: get mixed socks state
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONResult'
      security:
      - BasicAuth: []
      summary: state
      tags:
      - Operate
  /api/stop:
    post:
      description: stop mixed socks
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONResult'
      security:
      - BasicAuth: []
      summary: stop
      tags:
      - Operate
  /api/user:
    get:
      description: List all user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONResult'
      security:
      - BasicAuth: []
      summary: list
      tags:
      - User
    post:
      description: create or update user
      parameters:
      - description: user
        in: body
        name: scripts
        required: true
        schema:
          $ref: '#/definitions/service.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONResult'
      security:
      - BasicAuth: []
      summary: save
      tags:
      - User
  /api/user/{username}:
    delete:
      description: delete user
      parameters:
      - description: username
        in: path
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONResult'
      security:
      - BasicAuth: []
      summary: delete
      tags:
      - User
  /version:
    get:
      description: 当前服务器版本
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Info'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONResult'
      summary: Version
      tags:
      - Version
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
